all:
	g++ -o test_reverse_statement reverse_statement.cpp -std=c++17
	g++ -o ip_to_uint ip_to_uint.cpp
	g++ -o add_two_string add_two_string.cpp
clean:
	rm -rf test_reverse_statement
	rm -rf ip_to_uint
	rm -rf add_two_string
